{% for displaytracks in artistMusicTracks %}
<div class="artist-profile-music-player">
    <div class="artist-profile-project-image">Artist Image Here</div>
    <div class="artist-profile-control-wrapper">
        <audio controls>
            <!--source src="{{ displaytracks.full }}" type="audio/mpeg"-->
            <source src="/public/assets/m3Mb3rz/1/media/music/projects/bangersickfreedl.mp3" type="audio/mpeg">
        </audio>
    </div>
    <div class="player-profile-icons-wrapper">
        <div class="vlog-social-icon">
            <a href="#">
                <i class="fa fa-twitter fa-2x"></i>
            </a>
        </div>
        <div class="vlog-social-icon">
            <a href="#">
                <i class="fa fa-facebook fa-2x"></i>
            </a>
        </div>
        <!--div class="vlog-social-icon">
            <a href="#">
                <i class="fa fa-snapchat fa-2x"></i>
            </a>
        </div-->
        <!--div class="vlog-social-icon">
            <a href="#">
                <i class="fa fa-instagram fa-2x"></i>
            </a>
        </div-->
    </div>
</div>
{% endfor %}