{% extends "template/layout/memberprofiletemplate.phtml" %}
{% block cpanelcontent  %}
<div class="member-profile-billboard-wrapper">
    <div class="member-profile-billboard-img-container" id="upload-profile-billboard">
        <a href="#">
            <img class="member-profile-billboard-img" src="{{ billboard }}" title="" >
            <div class="inner-billboard-image-form">
                <div class="inner-billboard-image-form-text">
                    Upload New Photo
                </div>
                <i class="fa fa-camera fa-3x" aria-hidden="true" ></i>
            </div>
        </a>
    </div>
</div>
<div class="member-profile-edit-bar">
    <div class="member-profile-thumbnail-container">
        <div class="member-profile-thumbnail-wrapper" id="upload-profile-thumbnail">
            <a href="#">
                <img class="member-profile-thumbnail-image" src="{{ thumbProfile }}">
                <div class="inner-thumb-image-form">
                    <i class="fa fa-camera fa-1x" aria-hidden="true" ></i>
                </div>
            </a>
        </div>
        <div class="member-profile-thumbnail-text">@{{ username }}</div>
    </div>
    <script>
        $(document).ready(function () {
            $("div#thumbnail-image-form").hide();
            $("div#billboard-image-form").hide();
            $('div#gif-div').hide();
            $('div#gif-dialog').hide();
            $('div.inner-thumb-image-form').hide();
            $('div.inner-billboard-image-form').hide();
            $('div#file-type').hide();
            $("div#file-ext").hide();
            $("div#file-size").hide();

            // show form option with mouse over effect
            $("#upload-profile-billboard").on('mouseover', function(){
                $('div.inner-billboard-image-form').show();
            });
            $("#upload-profile-billboard").on('mouseout', function(){
                $('div.inner-billboard-image-form').hide();
            });

            // show form option with mouse over effect
            $("#upload-profile-thumbnail").on('mouseover', function(){
                $('div.inner-thumb-image-form').show();
            });
            $("#upload-profile-thumbnail").on('mouseout', function(){
                $('div.inner-thumb-image-form').hide();
            });

            // upload billboard image function
            $("#upload-profile-billboard").on('click', function () {

                $("div#gif-dialog").dialog({
                    width: 450,
                    height: 200,
                });
                setTimeout(function() {
                    $("div#gif-dialog").dialog('close')
                },2500);


                var showGif = setInterval(openUploadImageForm, 1000);
                $("#gif-div").html('<img src="../../assets/images/miniLoader.gif" class="gif-div-image">').show(showGif);

                function openUploadImageForm() {
                    $('#gif-div').hide();
                    $("div#gif-dialog").hide();
                    $("div#billboard-image-form").dialog({
                        width: 450,
                        height: 200
                    });
                    stopInterval();
                }

                function stopInterval(){
                    clearInterval(showGif);
                    return false;
                }
            });

            // upload thumb nail image function
            $("#upload-profile-thumbnail").on('click', function () {

                $("div#gif-dialog").dialog({
                    width: 450,
                    height: 200,
                });
                setTimeout(function() {
                    $("div#gif-dialog").dialog('close')
                },2500);

                var showGif = setInterval(openUploadImageForm, 1000);
                $("#gif-div").html('<img src="../../assets/images/miniLoader.gif" class="gif-div-image">').show(showGif);

                function openUploadImageForm() {
                    $('#gif-div').hide();
                    $("div#thumbnail-image-form").dialog({
                        width: 450,
                        height: 200
                    });
                    stopInterval();
                }

                function stopInterval(){
                    clearInterval(showGif);
                    return false;
                }
            });
        });
    </script>
    <div id="gif-dialog" title="Fetching Form...."><img src="../../assets/images/miniLoader.gif" class="gif-div-image"></div>
    <div id="billboard-image-form" title="Upload Billboard Image">{% include '/partials/billboard-image-form.phtml' %}</div>
    <div id="thumbnail-image-form" title="Upload Thumbnail Image">{% include '/partials/thumbnail-image-form.phtml' %}</div>
    <!--div id="error-messages-dialog" title="Image Error:">{% include '/partials/error-messages.phtml' %}</div-->
    <div class="profile-edit-bar-content">
        <div class="profile-edit-setting">
            <a href="/appcms/cpanel/index">CPANEL</a>
        </div>
        <div class="profile-edit-setting">
            <a href="/appcms/users/index">EDIT PROFILE</a>
        </div>
        <div class="profile-edit-setting">
            <a href="/appcms/users/artistbio">EDIT BIO</a>
        </div>
        <div class="profile-edit-setting">
            <a href="/appcms/music/index">EDIT MUSIC</a>
        </div>
        <div class="profile-edit-setting">
            <a href="/appcms/video/index">EDIT VIDEO</a>
        </div>
    </div>
</div>
<div class="artist-projects-thumb-slider">
    <h1 class="home-page-h1">NEW MEMBERS</h1>
    <div class="artist-projects-thumb-slider-prev-button">
        <button type="button" id="prev1" value="PREV">PREV</button>
    </div>
    <div class="cycle-slideshow"
         data-cycle-fx=carousel
         data-cycle-carousel-visible=5
         data-cycle-timeout=6000
         data-cycle-next="#next1"
         data-cycle-prev="#prev1">
        {% for key, displaythumbs in cdThumbCovers %}
            <img class="cycle-slideshow-img" title="" src="{{ displaythumbs }}" >
        {% endfor %}
    </div>
    <div class="artist-projects-thumb-slider-next-button">
        <button type="button" id="next1" value="NEXT">NEXT</button>
    </div>
</div>
<div class="member-content-wrapper">
    <div class="member-profile-widget-container">
        {% if stepsToOwn == 'step1Completed' %}
            {% include '/partials/cta_step_2.phtml' %}
        {% elseif stepsToOwn == 'step2Completed' %}
            {% include '/partials/cta_step_3.phtml' %}
        {% endif %}
        <div class="twitter-widget">
            <a class="twitter-timeline"  href="https://twitter.com/HomeGrownMusiq" data-widget-id="365114738276970500">Tweets by @HomeGrownMusiq</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
        </div><hr>
        <div class="widget-ad-banner">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- cpanel-ad-banner -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-3000506446152743"
                 data-ad-slot="4361994840"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
    <div class="member-profile-content">
        {% include '/partials/jplayer.phtml' %}
        <div class="artist-profile-music-player">
            <div class="artist-profile-project-image">Artist Image</div>
            <div class="artist-profile-control-wrapper">
                <!--audio src="../../m3Mb3rz/{{ userId }}/media/music/projects/bangersickfreedl.mp3" controls autoplay-->
                <audio controls autoplay>
                    <source src="bangersickfreedl.mp3" type="audio/mpeg">
                </audio>
            </div>
        </div>
    </div>
    <script>
        $(document).ready(function(){
            // check profile and billboard images error messages
           /* var errorMsg = {{ errorMsg }}
            if(errorMsg !== ""){
                alert(errorMsg);
            }*/

            /*if(errorMsg === "Sorry, file already exists."){

                $("#error-messages-dialog").html('<div class="gif-div-image"> + errorMsg + </div>').show();

                $("div#error-messages-dialog").dialog({
                    width: 450,
                    height: 200,
                });
            }*/

            // initial
           //$('.member-profile-content').load('/music/artistplayer');

           // handle click request
            $('.profile-edit-setting a').click(function(){
                var page = $(this).attr('href');
                //alert(page);
                $('.member-profile-content').load(page);
                return false // to prevent default click
            });
        });
    </script>
</div>
{% endblock %}