{% extends "template/layout/appcmscpaneltemplate.phtml" %}
{% block cpanelcontent  %}
<div id="cPanPages">
    <h1>{{ pageTitle }}</h1>
    <div class="breadcrumb-font"><a href="{{ indexpage }}"><< {{ breadcrumb_index }} Home</a></div>
    <hr>
    <div class="row">
        <div class="tinymce-editor-wrapper">
            <form action="{{ processuploadPageContent }}" method="post"  class="edit-page-editor" name="{{ uploadPageContentFormName }}">
                <label>Page Editor:  You are editing the {{ pageName }} page </label>
                <textarea id="editcorepages" name="editcorepages" title="">{{ pageContent }}</textarea>
                <input type="hidden" name="csrf_token" value="{{ csrftoken }}" >
                <input type="submit" value="SAVE" class="corepages-submit-button" name="corepages_SubmitBtn" />
            </form>
        </div>
    </div>
</div>
{% endblock %}