{% block maincontent %}
<div style="padding:12px; font-size:17px; width:800px;">
    <h3>Welcome To {{ siteName }} </h3>
    Hello New Member,<br /><br />

    Thank you for registering at {{ siteName }} and joining our community!<br /><br />

    You are almost ready to log into {{ siteName }} after you have successfully completed the activation process using your:<br /><br />

    REGISTERED email address and password.<br /><br />

    Click on the provided link, that we just sent to your email to complete the process.<br /><br />

    Thank you,<br /><br />

    TEAM {{ siteName}} !!
</div>
{% endblock %}