<!DOCTYPE html>
<html>
{% include 'template/layout/pagehead.phtml' %}
<body>
    <!--script type="text/javascript" src="/resources/js/socials/fb_hgm_web_sdk.js"></script-->
    <script>
        window.fbAsyncInit = function() {
            FB.init({
                appId      : '1657457384504318',
                xfbml      : true,
                version    : 'v2.9'
            });
            FB.AppEvents.logPageView();
        };

        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) {return;}
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/en_US/sdk.js";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
   <div class="container-fluid page-content-wrapper">
       <!-- START HEADER CONTAINER -->
       <div class="row">
           <div id="mast-head-wrapper" class="mast-head-wrapper" >
               {% include 'template/layout/header.phtml' %}
           </div>
       </div>
       <!-- #end Header wrapper -->

       <!--Start Main Content Wrapper -->
       <div class="row">
           <div class="main-content-wrapper">
               <div class="main-content">
                   <h1> {{ pageTitle }} </h1>
                    {% block maincontent %}
                    {% endblock %}
               </div>
               {% include 'template/layout/banners/std_lowerpage_banner.phtml' %}
           </div><!-- #end main content wrapper -->
       </div>


       <!-- Push the footer to bottom of page -->
       <div class="row">
            <div class="push_footer_down"></div>
       </div>

       <!-- START FOOTER CONTAINER -->
       <div class="row">
           <div class="footer-wrapper">
                {% include 'template/layout/footer.phtml' %}
           </div>
       </div><!-- #end Footer wrapper -->

   </div>

</body>
</html>