<footer>
    <!-- START FOOTER NAV WRAPPER -->
    <div class="footer-nav">
        <ul>
            <li><a href="/">{{ siteName }} &copy; <?php echo date('Y');?></a></li>
            <li><a href="/about/index">ABOUT</a></li>
            <li><a href="/memberz/index">MEMBERS</a></li>
            <li><a href="/services/index">SERVICES</a></li>
            <li><a href="/vlog/index">VLOG</a></li>
            <li><a href="/terms/index">TERMS</a></li>
            <li><a href="/blog/index">BLOG</a></li>
            <li><a href="/privacy/index">PRIVACY</a></li>
            <li><a href="/socials/index">FIND US</a></li>
            <li><a href="/login/index">LOGIN</a></li>
            <li><a href="/contact/index">CONTACT</a></li>
            <li><a href="/register/index">REGISTER</a></li>
        </ul>
        <!--span id="siteseal">
        <script async type="text/javascript" src="https://seal.godaddy.com/getSeal?sealID=IKMVc5wgfNexHdxHlIEuFFVuv12EMub0QIVYeK1sVjy9oonmBVUMeG8PmyBB"></script>
        </span-->
    </div>
    <div class="site-footer">
        {{ siteName }} &copy; <?php echo date('Y');?>
        <a href="/">
        </a> is powered by getMarvelle CMS.  getMarvelle CMS is a copyrighted and a registered trademark. This site was develop by webmaster
        <a href="http://www.marvintdawson.com">Marvin Dawson</a>. Hosted by Home Grown Musiq Network LLC.
    </div>
</footer>