<head>
    <meta charset="utf-8">
    <meta name ="Keywords" content="{{ siteKeywords }}"/>
    <meta name="description" content="{{ pageDescription }}" />
    <meta name="rating" content="General"/>
    <meta name="ROBOTS" content="All" />
    <meta name="revisit-after" content="7 days" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <meta property="fb:app_id" content="1657457384504318" />
    <meta property="og:url" content="{{ fbOGUrl }}" />
    <meta property="og:type" content="{{ fbOGType }}" />
    <meta property="og:title" content="{{ fbOGTitle }}" />
    <meta property="og:description" content="{{ fbOGDescription }}" />
    <meta property="og:image" content="{{ fbOGImage }}" />

    <!-- stylesheets -->
    <link href="/resources/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" >
    <link href="/resources/font_awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" >
    <link href="/resources/uikit/css/uikit.min.css" rel="stylesheet" >
    <link href="/resources/css/header.css" rel="stylesheet" >
    <link href="/resources/css/footer.css" rel="stylesheet" >
    <link href="/resources/css/main_content.css" rel="stylesheet" >
    <link href="/resources/css/cpan_form_base.css" rel="stylesheet" >
    <link href="/resources/css/form_base.css" rel="stylesheet" >
    <link href="/resources/css/banners.css" rel="stylesheet" >
    <link href="/resources/css/slide_shows.css" rel="stylesheet" >
    <link href="/resources/css/hgmradioplayer.css" rel="stylesheet" >
    <link href="/resources/css/stationconsole.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600" rel="stylesheet">
    <link href="/resources/css/css/styles.css" rel="stylesheet" >
    <!--link href="/resources/css/app.css" rel="stylesheet"-->
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="/assets/jPlayer/dist/skin/pink.flag/css/jplayer.pink.flag.css">

    <!-- jquery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="/resources/jplayer/jplayer/dist/jplayer/jquery.jplayer.js"></script>
    <!--script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.js"></script-->

    <!-- jquery cycle plugin -->
    <script type="text/javascript" src="/resources/js/jquery/jquery.cycle2.min.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/jquery.cycle2.carousel.min.js"></script>
    <!--script type="text/javascript" src="/resources/js/jquery/jquery.cycle.all.js"></script-->

    <!-- tinymce js -->
    <script type="text/javascript" src="/resources/js/tinymce/js/tinymce/tinymce.min.js"></script>

    <!-- site js -->
    <script type="text/javascript" src="/resources/js/jquery/jquery_function_controllers.js"></script>
    <script type="text/javascript" src="/resources/js/form_validation.js"></script>
    <script type="text/javascript" src="/resources/js/tinymce_selectors.js"></script>
    <script type="text/javascript" src="/resources/js/jquery/themelayout.js"></script>
    <script type="text/javascript" src="/resources/js/hgmplayer.js"></script>

    <!-- fav icon -->
    <link rel="shortcut icon" href="/assets/images/favicon.ico" type="image/x-icon" />
    <link rel="icon" href="/assets/images/favicon.ico" type="image/x-icon" />

    <title>{{ tabTitle }}</title>
</head>