<div class="profile-call-to-action">
    <div class="cta-step-topic">
        You're ready to complete: <span class="cta-step">STEP 3</span> <br/> to activate your FREE website!
    </div>
    <a href="/appcms/hgmclient/enterdomain">
        <div class="profile-call-to-action-button">
            <div class="profile-call-to-action-text">
                Enter Domain Name
            </div>
        </div>
        <div class="cta-subtopic-link">
            <a href="#">
                I've already entered my domain.
            </a>
        </div>
    </a>
</div>