<div class="profile-call-to-action">
    <div class="cta-step-topic">
        You are ready to complete: <span class="cta-step">STEP 2</span> <br/> and own your brand name!
    </div>
    <a href="http://store.homegrownmusiq.com">
        <div class="profile-call-to-action-button">
            <div class="profile-call-to-action-text">
                Purchase Domain Name
            </div>
        </div>
        <div class="cta-subtopic-link">
            <a href="#">
                I've already purchased a domain.
            </a>
        </div>
    </a>
</div>