{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class="corepage-wall">
    <img src="../assets/images/promos/grow_home_grown_dope_base_1200_x_650_website.jpg" class="corepage_wall_image">
</div>
<div class = "main-content-tier1-wrapper" >
    <div class="promos-get-started-button">
        <a href="/promos/ogkush_learn_how">
            <div class="promos-get-started-button-font">
                LEARN HOW
            </div>
        </a>
    </div>
</div >
{% endblock %}