{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class = "main-content-tier1-wrapper" >
    <h4>Get a free website template and 1 year of web hosting in 3 steps.</h4>
    <ul>
        <li>Step 1. Become a HomeGrownMusiq.com member</li>
        <li>Step 2. Purchase your "Artist Domain Name" (requires a separate registration to management your artist or label domain name ownership).</li>
        <li>Step 3. Sign back into HomeGrownMusiq.com and enter your newly purchased artist domain and we do the rest.</li>
    </ul>
    <div class="promos-get-started-button">
        <a href="/register/index">
            <div class="promos-get-started-button-font">
                GET STARTED
            </div>
        </a>
    </div>
</div >
<div class="main-content-tier2-wrapper">

        <h2>Frequently Asked Questions</h2>
    <div class="faq-div-wrapper">
        <h4>What's the catch?</h4>
        <p>No catch, we want to help independent artist get started that's it.  All you have to do is purchase your artist or label domain name at $12.99 annually.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>Are there any additional hidden cost?</h4>
        <p>No, the OG Kush promotion has no additional hidden cost.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>Can I customize my theme?</h4>
        <p>No, the free Jukebox theme can not be customize, outside of the domain name, contact info, standard photos and music uploads.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>How long does the FREE web hosting last?</h4>
        <p>1 year (12 calendar months), after the 1 year time has expired, the cost to keep the website starts at $49.99 annually.
            This does not include the potential annual cost for any previously purchased domain name. Domain name cost is separate.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>How long does it take to setup up the site?</h4>
        <p>On a average it can take up to 24 hours to confirm a domain purchase for proper registration. In some cases setup has been reported to take less than 2 hours.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>How many CDs can I upload?</h4>
        <p>Currently we are entertaining the idea of 5 CDs to promote.</p>
    </div><hr>
    <div class="faq-div-wrapper">
        <h4>Can I connect or post to Social Media?</h4>
        <p>Yes, we are adding this option to the Jukebox theme.</p>
    </div><hr>
</div>
{% endblock %}