{% extends "template/layout/memberprofiletemplate.phtml" %}
{% block cpanelcontent %}
<div class="member-profile-billboard-wrapper">
    <div class="member-profile-billboard-img-container">
        <a href="">
            <img class="member-profile-billboard-img" src="{{ billboard }}" title="" >
        </a>
    </div>
</div>
<div class="member-profile-edit-bar">
    <div class="member-profile-thumbnail-container">
        <div class="member-profile-thumbnail-wrapper">
            <a href="#">
                <img class="member-profile-thumbnail-image" src="{{ thumbProfile }}">
            </a>
            <div class="member-profile-thumbnail-text">@{{ username }}</div>
        </div>
        <div class="profile-edit-bar-content">
            <div class="profile-edit-setting">
                <a href="/profile/artistbio">BIO</a>
            </div>
            <div class="profile-edit-setting">
                <a href="/profile/artistmusic">MUSIC</a>
            </div>
            <div class="profile-edit-setting">
                <a href="/profile/artistvideos">VIDEO</a>
            </div>
        </div>
    </div>
</div>
<div class="member-content-wrapper">
    <div class="member-profile-widget-container">
        <div class="widget-ad-banner">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- cpanel-ad-banner -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-3000506446152743"
                 data-ad-slot="4361994840"
                 data-ad-format="auto"></ins>
            <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>
    <div class="member-profile-content"></div>
</div>
{% endblock %}