{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
<div class = "main-content-tier1-wrapper" >
    <p> {% include "template/layout/banners/corepages_336x280_banner.phtml" %}  {{ pageContent }} </p >
    <h5>PRIVACY</h5>
    <p>All data collected during the time of registration and use of HomeGrownMusiq.com website and HGM Radio Mobile App, will remain private data of the
        Home Grown Musiq Network LLC.</p>

    <h5>COPYRIGHT</h5>
    <p>If it has be determined, and or that a claim has been filed against any artist for uploading copyright material in the form of lyrics,
        music, vocals, unauthorized samples, art, photos, pictures in which the artist in question does not have the legal right to redistribute, rebroadcast or make ownership claims to:
    <ul>
        <li>A.  The artist in question website could potentially be marked as inactive until further claims have been disproved. </li>
        <li>
            B. Each artist will be given 30 days to argue their claim, in which the party making the claim can appeal the argue in 30 days.
            This process could take up to but not limited to 60 days for appeal and reconciliation.    During that time the material in question
            will not be made available to the public for consumption or use.
        </li>
    </ul>
    </p>
</div >
{% endblock %}