{% extends "template/layout/basetemplate.phtml" %}
{% block maincontent %}
    <section class="vlog-globalroll">
        <div class="vlog-videoWrapper">
            <h2>"Video Goes Here! </h2>
            <video class="video-container" controls>
                <source src="../../../../assets/media/video/vlogcast/Does_Gorilla_Posting_Work.mp4" title="Microsoft Bug" type="video/mp4">
            </video>
        </div>
        <!-- Start Vlog Author -->
        <div class="vlog-infoWrapper">
            <div class="vlog-site-hash">
                <?php echo "#HomeGrownMusiq"; ?>
            </div>
            <div class="vlog-social-icons-wrapper">
                <div class="vlog-social-icon">
                    <a href="#">
                        <i class="fa fa-snapchat fa-2x"></i>
                    </a>
                </div>
                <div class="vlog-social-icon">
                    <a href="#">
                        <i class="fa fa-instagram fa-2x"></i>
                    </a>
                </div>
                <div class="vlog-social-icon">
                    <a href="#">
                        <i class="fa fa-twitter fa-2x"></i>
                    </a>
                </div>
                <div class="vlog-social-icon">
                    <a href="#">
                        <i class="fa fa-facebook fa-2x"></i>
                    </a>
                </div>
            </div>

        </div><!-- /end  -->
        <article>
            <!-- Start Vlog Title -->
            <div class="vlog-titleWrapper">
            </div><!-- /end  -->
            <!-- Start Vlog Article  -->
            <div class="vlog-articleWrapper">
                {{ pageContent }}
            </div><!-- /end  -->
        </article>
    </section>
{% include '/partials/blog_subscribe.phtml' %}

{% endblock %}